version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: echo_app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=echo
      - DB_PORT=5432
      - REDIS_ADDR=redis:6379
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: echo_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: echo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: echo_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata:
